### ISSUE TITLE
Wrong date format for x-amz-date

### ISSUE THREAD

**Issue by eterry1388** [Shikisoft/rails-ng-s3-sigv4-example#1]
You are using `%Y%jT%H%M%SZ` here:
https://github.com/Shikisoft/rails-ng-s3-sigv4-example/blob/be8a8dc0e2b431e7b07264f645f50d8bb6a0479a/app/controllers/policy_controller.rb#L12

Which is making the date look like this: `202000101....` . `%j` is for day of year.

This is the correct format:  `%Y%m%dT%H%M%SZ`.

This issue presented itself for us on Jan 1st, 2020.

**Comment by yilmaz-emre** [comment]
Thanks for the notification, I pushed an update today. 

This was an old example which I wrote and tested almost 2.5 years ago while writing a blog post. Actually, I do not remember why I used `%j` at that time, but it was clearly wrong as I also received a "policy expired" error when I tested today. Now it works again after replacing `%j` with `%m%d` as you noted.

By the way, I also upgraded the example to use Rails 4.2.11 and Ruby 2.4 because of the issues resulting from openssl version 1.1 mismatch with Ruby 2.2.
